platform :ios, '10.0'

target 'SwiftDemoApp' do
  use_frameworks!
 pod 'OptimoveSDK','2.0.0'
end

target 'Notification Extension' do
    use_frameworks!
    pod 'OptimoveNotificationServiceExtension', '1.3.0'
end
